### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by iclassdon** [ssypchenko/GG1MapChooser#12]
When changing any of these settings time settings to true. 

  "TimeLimitSettings": {
    "VoteDependsOnTimeLimit": false,
    "TriggerSecondsBeforeEnd": 35,
    "ChangeMapAfterTimeLimit": true,
    "VoteNextRoundStartAfterTrigger": false

The console prints out this error: 

[09:00:48.770] CSSharp: Native 7a5bae39 was invoked on a non-main thread
Unhandled exception. CounterStrikeSharp.API.Core.NativeException: Invoked on a non-main thread
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.CreateTimer(Single interval, InputArgument callback, Int32 flags) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1254
   at CounterStrikeSharp.API.Modules.Timers.Timer..ctor(Single interval, Action callback, Nullable`1 flags) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Timers/Timer.cs:line 34
   at CounterStrikeSharp.API.Core.BasePlugin.AddTimer(Single interval, Action callback, Nullable`1 flags) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 355
   at MapChooser.MapChooser.<>c__DisplayClass176_0.<<StartOrRestartTimeLimitTimer>b__0>d.MoveNext() in /Users/sergeysypchenko/css-development/GG1MapChooser/GG1MapChooser.cs:line 2733
--- End of stack trace from previous location ---
   at MapChooser.TimerManager.<>c__DisplayClass7_0.<<ProcessQueueAsync>b__0>d.MoveNext() in /Users/sergeysypchenko/css-development/GG1MapChooser/GG1MapChooser.cs:line 3343
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
./game/cs2.sh: line 98:   105 Aborted                 (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

**Comment by ssypchenko** [comment]
What version do you use?

**Comment by iclassdon** [comment]
This error was on GG1MapChooser.1.5.1.  I upgraded from v1.4.4
